name: mxnet-ci
dependencies:
  - cudatoolkit = 9.2
  - pip
  - pip:
    - --pre mxnet-cu92
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm
