name: mxnet-ci
dependencies:
  - cudatoolkit = 9.2
  - pip
  - pip:
    - mxnet-cu92==1.6.0b20190903
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm
